"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EndScreen = EndScreen;
const jsx_runtime_1 = require("react/jsx-runtime");
const StatBar_1 = require("../components/StatBar");
function EndScreen({ outcome, stats, loseReason, selectedClass, onRestart }) {
    const isWin = outcome === 'win';
    return ((0, jsx_runtime_1.jsx)("div", { className: "flex min-h-screen flex-col items-center overflow-y-auto bg-gray-950 p-6 text-gray-100", children: (0, jsx_runtime_1.jsxs)("div", { className: "w-full max-w-2xl", children: [(0, jsx_runtime_1.jsxs)("div", { className: `mb-8 rounded-2xl border-2 p-6 text-center ${isWin ? 'border-green-600 bg-green-900/20' : 'border-red-700 bg-red-900/10'}`, children: [(0, jsx_runtime_1.jsx)("div", { className: "mb-4 text-6xl", children: isWin ? '🏆' : '💀' }), (0, jsx_runtime_1.jsx)("h1", { className: `mb-2 text-3xl font-black tracking-widest ${isWin ? 'text-green-400' : 'text-red-400'}`, style: { fontFamily: 'Cinzel Decorative, serif' }, children: isWin ? 'PROJECT DELIVERED' : 'PROJECT CANCELLED' }), loseReason && (0, jsx_runtime_1.jsx)("p", { className: "mt-2 text-sm italic text-red-300", children: loseReason }), (0, jsx_runtime_1.jsxs)("p", { className: "mt-2 text-sm text-gray-400", children: [selectedClass?.emoji, " ", selectedClass?.name, " \u2014 ", selectedClass?.abilityName] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "mb-6 rounded-xl border border-gray-800 bg-gray-900 p-4", children: [(0, jsx_runtime_1.jsx)("h2", { className: "mb-4 text-xs font-bold tracking-widest text-purple-300", children: "\uD83D\uDCCA FINAL PROJECT METRICS" }), (0, jsx_runtime_1.jsx)(StatBar_1.StatBar, { label: "Budget", value: stats.budget, emoji: "\uD83D\uDCB0" }), (0, jsx_runtime_1.jsx)(StatBar_1.StatBar, { label: "Client Happiness", value: stats.clientHappiness, emoji: "\uD83D\uDE0A" }), (0, jsx_runtime_1.jsx)(StatBar_1.StatBar, { label: "Team Morale", value: stats.teamMorale, emoji: "\uD83D\uDCAA" }), (0, jsx_runtime_1.jsx)(StatBar_1.StatBar, { label: "Delivery Progress", value: stats.deliveryProgress, emoji: "\uD83D\uDE80" }), (0, jsx_runtime_1.jsx)(StatBar_1.StatBar, { label: "Technical Debt", value: stats.technicalDebt, emoji: "\uD83D\uDD77\uFE0F", inverted: true }), (0, jsx_runtime_1.jsx)(StatBar_1.StatBar, { label: "Compliance Risk", value: stats.complianceRisk, emoji: "\u2696\uFE0F", inverted: true })] }), (0, jsx_runtime_1.jsx)("div", { className: "text-center", children: (0, jsx_runtime_1.jsx)("button", { onClick: onRestart, className: "cursor-pointer rounded-xl bg-purple-700 px-8 py-4 text-lg font-bold tracking-widest text-white transition-all duration-200 hover:bg-purple-600 active:scale-95", children: "\uD83D\uDD04 NEW ENGAGEMENT" }) })] }) }));
}
