import { Room } from '../types/game';

export const FALLBACK_ROOMS: Room[] = [
  {
    id: 'lobby',
    floor: 1,
    roomNumber: 1,
    roomName: 'The Lobby of Vague Requirements',
    description: 'You enter a fog-filled reception hall. Somewhere behind a frosted glass partition, a stakeholder gestures vaguely at a whiteboard covered in arrows pointing to more arrows. "We want something like… you know, AI. But for our business. Can you do that by Q3?"',
    enemy: 'Vague Stakeholder',
    actions: [
      { id: 'a1', label: 'Run a Discovery Workshop', effectHint: 'Clarify requirements. Boosts morale and client happiness.' },
      { id: 'a2', label: 'Build What You Think They Mean', effectHint: 'Ship fast. Progress up, but technical debt lurks.' },
      { id: 'a3', label: 'Ask for Success Criteria in Writing', effectHint: 'Slow and painful. Reduces risk, frustrates client briefly.' },
      { id: 'a4', label: 'Nod Enthusiastically and Leave', effectHint: 'Nothing happens. Until it does.' },
    ],
    isBoss: false,
  },
  {
    id: 'jira',
    floor: 1,
    roomNumber: 2,
    roomName: 'The Jira Swamp',
    description: 'A vast, murky swamp stretches before you. Thousands of tickets float on the surface. The Backlog Troll emerges from beneath a pile of "TO DO" stickies, 847 unrefined stories clutched in its claws. It opens its mouth: "I\'ve just added seven more stories. They\'re all Priority 1."',
    enemy: 'Backlog Troll',
    actions: [
      { id: 'b1', label: 'Refine Every Ticket', effectHint: 'Methodical. Morale drops but debt shrinks.' },
      { id: 'b2', label: 'Delete Obvious Duplicates', effectHint: 'Quick win. Progress up, client slightly confused.' },
      { id: 'b3', label: 'Sprint Anyway', effectHint: 'Chaos. Progress surge, technical debt explodes.' },
      { id: 'b4', label: 'Rename All Tickets to Epics', effectHint: 'Looks productive. Nothing actually changes.' },
    ],
    isBoss: false,
  },
  {
    id: 'gdpr',
    floor: 2,
    roomNumber: 3,
    roomName: 'The GDPR Crypt',
    description: 'The air smells of legal disclaimers and cold sweat. A translucent wraith drifts through the server racks, whispering Article 17. "You are using personal data for model training," it hisses. "Consent form? What consent form?"',
    enemy: 'GDPR Wraith',
    actions: [
      { id: 'c1', label: 'Invoke Data Minimization', effectHint: 'Compliance risk drops significantly. Delivery slows.' },
      { id: 'c2', label: 'Use Synthetic Test Data', effectHint: 'Smart move. Both compliance and progress improve.' },
      { id: 'c3', label: 'Ask Legal for Approval', effectHint: 'Correct but slow. Risk falls, budget takes a hit.' },
      { id: 'c4', label: 'Hope Nobody Notices', effectHint: 'They will notice. They always notice.' },
    ],
    isBoss: false,
  },
  {
    id: 'legacy',
    floor: 2,
    roomNumber: 4,
    roomName: 'The Legacy System Catacombs',
    description: 'Deep beneath the client\'s IT department lies a labyrinth of COBOL and Access databases. A monolith the size of a small moon pulses with malevolent energy. The last consultant who looked at the codebase never returned. The documentation is from 2004 and written in Comic Sans.',
    enemy: 'Legacy Monolith',
    actions: [
      { id: 'd1', label: 'Wrap It in an API', effectHint: 'Pragmatic. Debt up slightly, progress up significantly.' },
      { id: 'd2', label: 'Refactor Carefully', effectHint: 'Noble. Debt reduces, but pace is slow and budget hurts.' },
      { id: 'd3', label: 'Pretend the Documentation Is Accurate', effectHint: 'Fast initially. Catastrophic later.' },
      { id: 'd4', label: 'Recommend a Full Rewrite', effectHint: 'Client furious. But technically correct.' },
    ],
    isBoss: false,
  },
  {
    id: 'kubernetes',
    floor: 3,
    roomNumber: 5,
    roomName: 'The Kubernetes Furnace',
    description: 'A roaring chamber of spinning pods and crashing deployments. The Kubernetes Hydra has 9 heads, each running a different microservice. Three are in CrashLoopBackOff. One is on fire. "It was working in staging," whispers a developer ghost in the corner.',
    enemy: 'Kubernetes Hydra',
    actions: [
      { id: 'e1', label: 'Apply a Helm Chart', effectHint: 'Progress up. Technical debt may increase.' },
      { id: 'e2', label: 'Roll Back to Last Stable Version', effectHint: 'Safe but no progress. Morale preserved.' },
      { id: 'e3', label: 'Add More Pods', effectHint: 'Budget hit. Problem persists but louder.' },
      { id: 'e4', label: 'kubectl delete pod --all --force', effectHint: 'Chaotic. Might work. Definitely not best practice.' },
    ],
    isBoss: false,
  },
  {
    id: 'steering',
    floor: 3,
    roomNumber: 6,
    roomName: 'The Stakeholder Council',
    description: 'A circular chamber where twelve stakeholders sit in judgment. They have conflicting KPIs, conflicting opinions, and conflicting calendars. "When is this done?" asks one. "When can we see a demo?" asks another. "What even is AI?" asks a third.',
    enemy: 'Alignment Vampire',
    actions: [
      { id: 'f1', label: 'Present a Status Dashboard', effectHint: 'Transparency. Client happiness up, morale steady.' },
      { id: 'f2', label: 'Schedule Individual 1:1s', effectHint: 'Slow but effective. Progress halts, politics resolved.' },
      { id: 'f3', label: 'Send a Detailed Email', effectHint: 'Nobody reads it. At least you tried.' },
      { id: 'f4', label: 'Propose a Governance Framework', effectHint: 'Stakeholders love this. Consultants hate it.' },
    ],
    isBoss: false,
  },
  {
    id: 'procurement',
    floor: 4,
    roomNumber: 7,
    roomName: 'The Procurement Maze',
    description: 'A labyrinthine dungeon of RFP forms, vendor questionnaires, and approval chains. The Procurement Goblin blocks the path holding a 47-page vendor evaluation spreadsheet. "Have you completed Annex D, Section 12, Sub-clause 4b?" it croaks.',
    enemy: 'Procurement Goblin',
    actions: [
      { id: 'g1', label: 'Fill Out Every Form', effectHint: 'Budget drained. Compliance risk dramatically reduced.' },
      { id: 'g2', label: 'Use an Existing Framework Agreement', effectHint: 'Smart. Budget preserved, progress continues.' },
      { id: 'g3', label: 'Find the Right Sponsor', effectHint: 'Escalation works. Budget hit, but goblin retreats.' },
      { id: 'g4', label: 'Call It a Proof of Concept', effectHint: 'Bypasses procurement. Risky compliance move.' },
    ],
    isBoss: false,
  },
  {
    id: 'boss',
    floor: 5,
    roomNumber: 8,
    roomName: '⚔️ The Boardroom Boss Arena',
    description: 'The final chamber. A vast boardroom with floor-to-ceiling windows overlooking a burning city skyline. The Scope Creep Dragon awakens from a throne of change requests, exhaling clouds of PowerPoint slides. "We were just thinking," it rumbles, "could we also add a mobile app? And blockchain? And make it real-time?" Its eyes glow with the fire of uncosted features.',
    enemy: 'Scope Creep Dragon 🐉',
    actions: [
      { id: 'h1', label: 'Present the MVP Roadmap', effectHint: 'Strong. Progress surges, dragon partially tamed.' },
      { id: 'h2', label: 'Negotiate Scope Formally', effectHint: 'Budget saved. Client respect earned.' },
      { id: 'h3', label: 'Promise Phase Two', effectHint: 'The classic. Dragon appeased for now. Budget at risk later.' },
      { id: 'h4', label: 'Deploy Live in the Meeting', effectHint: 'Legendary move. Huge progress, huge risk.' },
      { id: 'h5', label: 'Invoke the Change Request Process', effectHint: 'Procedurally correct. Dragon hates paperwork.' },
    ],
    isBoss: true,
  },
];

export const ROOM_SEQUENCE = ['lobby', 'jira', 'gdpr', 'legacy', 'kubernetes', 'steering', 'procurement', 'boss'];
